// <auto-generated />
using Customer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Customer.Data.Migrations
{
    [DbContext(typeof(CustomerDb))]
    [Migration("20201211133117_SeedDataUpdated")]
    partial class SeedDataUpdated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customeraccount")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Customer.Data.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AddressOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanPurchase")
                        .HasColumnType("bit");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerAuthId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequestedDeletion")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Active = true,
                            AddressOne = "85 Clifton Road",
                            AreaCode = "DL1 5DS",
                            CanPurchase = true,
                            CustomerAuthId = "f756701c-4336-47b1-8317-a16e84bd0059",
                            EmailAddress = "chris@example.com",
                            FamilyName = "Burrell",
                            GivenName = "Chris",
                            RequestedDeletion = false
                        },
                        new
                        {
                            CustomerId = 2,
                            Active = true,
                            AddressOne = "85 Clifton Road",
                            AreaCode = "DL1 5DS",
                            CanPurchase = true,
                            CustomerAuthId = "07dc5dfc-9dad-408c-ba81-ff6a8dd3aec2",
                            EmailAddress = "paul@example.com",
                            FamilyName = "Mitchell",
                            GivenName = "Paul",
                            RequestedDeletion = false
                        },
                        new
                        {
                            CustomerId = 3,
                            Active = true,
                            AddressOne = "85 Clifton Road",
                            AreaCode = "DL1 5DS",
                            CanPurchase = true,
                            CustomerAuthId = "1e3998f7-4ca6-42e0-9c78-8cb030f65f47",
                            EmailAddress = "jack@example.com",
                            FamilyName = "Ferguson",
                            GivenName = "Jack",
                            RequestedDeletion = false
                        },
                        new
                        {
                            CustomerId = 4,
                            Active = true,
                            AddressOne = "85 Clifton Road",
                            AreaCode = "DL1 5DS",
                            CanPurchase = true,
                            CustomerAuthId = "bce3bb9c-5947-4265-8a7d-8588655bbabe",
                            EmailAddress = "carter@example.com",
                            FamilyName = "Ridgeway",
                            GivenName = "Carter",
                            RequestedDeletion = false
                        },
                        new
                        {
                            CustomerId = 5,
                            Active = true,
                            AddressOne = "85 Clifton Road",
                            AreaCode = "DL1 5DS",
                            CanPurchase = true,
                            CustomerAuthId = "fb9e3941-6830-4387-be15-eeac14848c01",
                            EmailAddress = "karl@example.com",
                            FamilyName = "Hall",
                            GivenName = "Karl",
                            RequestedDeletion = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
